"""Initial

Revision ID: 7b698c1bde97
Revises: 
Create Date: 2023-05-27 19:45:16.337575

"""
from alembic import op
import sqlalchemy as sa

import db.generics

# revision identifiers, used by Alembic.
revision = '7b698c1bde97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_user_first_name'), 'user', ['first_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_last_name'), 'user', ['last_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_username'), 'user', ['username'], unique=True, schema='users')
    op.create_table('signins_history',
    sa.Column('user', db.generics.GUID(), nullable=False),
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signins_history', schema='users')
    op.drop_index(op.f('ix_users_user_username'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_last_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_first_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    op.execute("DROP SCHEMA users")
    # ### end Alembic commands ###