"""empty message

Revision ID: dd14a2484b06
Revises: 
Create Date: 2023-05-27 21:47:22.545040

"""
from alembic import op
import sqlalchemy as sa
import db.generics

# revision identifiers, used by Alembic.
revision = 'dd14a2484b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_right',
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('role',
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_user_first_name'), 'user', ['first_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_last_name'), 'user', ['last_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_username'), 'user', ['username'], unique=True, schema='users')
    op.create_table('user_access_right',
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('user_role',
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('accesstoken',
    sa.Column('user_id', db.generics.GUID(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', db.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('token'),
    schema='users'
    )
    op.create_index(op.f('ix_users_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False, schema='users')
    op.create_table('signins_history',
    sa.Column('user', db.generics.GUID(), nullable=False),
    sa.Column('id', db.generics.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signins_history', schema='users')
    op.drop_index(op.f('ix_users_accesstoken_created_at'), table_name='accesstoken', schema='users')
    op.drop_table('accesstoken', schema='users')
    op.drop_table('user_role', schema='users')
    op.drop_table('user_access_right', schema='users')
    op.drop_index(op.f('ix_users_user_username'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_last_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_first_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    op.drop_table('role', schema='users')
    op.drop_table('access_right', schema='users')
    # ### end Alembic commands ###