name: "CI: AUTH"

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: pre-commit
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install -r requirements/local.txt
          pre-commit run --show-diff-on-failure --color=always --all-files

  pytest:
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          file: "./compose/local/auth/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/stranded-in-python/movix-auth:dev
          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}

      - name: Run pytest
        run: pytest ./src/tests

  builder:
    environment: production
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Copy .dockerignore
        run: |
          cp ./compose/production/api/.dockerignore ./

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          file: "./compose/production/auth/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/stranded-in-python/movix-api:latest

          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}